name: Code Build

on:
  pull_request:
jobs:
  run-codelint-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Install dependencies
        run: make get-dependencies
      - name: Validate code
        run: make build
