name: Tests

on:
  push:
    branches:
      - "main"
      - "develop"
jobs:
  run-tests-on-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Install dependencies
        run: make get-dependencies
      - name: Validate code
        run: make tests
